### ISSUE TITLE
Animations are messed up on url

### ISSUE THREAD

**Issue by tawseefrstk** [tawseefrstk/tawseef-pages#2]
On a locally downloaded copy, it works fine, however on https://tawseef.tk there are some errors with the animations.

(The site just hosts this repo, so unsure of the issue.)

**Comment by NicholasG04** [comment]
Browser, when, how to reproduce?

**Comment by tawseefrstk** [comment]
# Browser
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0

# Steps to reproduce
Visit https://tawseef.tk using Mozilla Firefox.

# When

On page load/refresh on https://tawseef.tk.

**Comment by NicholasG04** [comment]
Except I'm using Firefox 67.0b2 without problems...

**Comment by tawseefrstk** [comment]
Fixed.
